##??? ??
spring:
  main:
    web-application-type: SERVLET
  ##????????
  datasource:
    hikari:
      jdbcUrl: jdbc:oracle:thin:@localhost:1521:orcl
      username: scott
      password: tiger
      connection-timeout: 15000
      minimum-idle: 5
      driver-class-name: oracle.jdbc.OracleDriver
      maximum-pool-size: 100
      max-lifetime: 1800000
      idle-timeout: 300000
      pool-name: HikariCP
      auto-commit: true
    url: jdbc:oracle:thin:@localhost:1521:orcl

  ##JSP ????
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false

  thymeleaf:
    cache: false
  servlet:
    multipart:
      resolve-lazily: false
      enabled: true
      file-size-threshold: 0B
      location: ${java.io.tmpdir}
      max-file-size: 50MB
      max-request-size: 50MB
##????
#: 0~1024 ???? (?????? ??)
#1024~ ????
#FTP 21
server:
  tomcat:
    additional-tld-skip-patterns: "*.jar"
    threads:
      max: 5 #생성할 수 있는 thread의 총 개수
      min-spare: 5 #항상 활성화 되어있는 (idle) thread의 갯수
    accept-count: 10 #작업 큐의 사이즈
  port: 8080
#WWW 8000~8999 ??? ??? ?? ????.
mybatis:
  configuration:
    map-underscore-to-camel-case: true